<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>
	Comments on: The Lock keyword	</title>
	<atom:link href="https://alex.ciobanu.org/?feed=rss2&#038;p=34" rel="self" type="application/rss+xml" />
	<link>https://alex.ciobanu.org/?p=34</link>
	<description>Yet Another Programming Blog</description>
	<lastBuildDate>Tue, 04 Aug 2009 15:47:28 +0000</lastBuildDate>
	<sy:updatePeriod>
	hourly	</sy:updatePeriod>
	<sy:updateFrequency>
	1	</sy:updateFrequency>
	<generator>https://wordpress.org/?v=5.2.2</generator>
			<item>
				<title>
				By: alex				</title>
				<link>https://alex.ciobanu.org/?p=34&#038;cpage=1#comment-469</link>
		<dc:creator><![CDATA[alex]]></dc:creator>
		<pubDate>Tue, 04 Aug 2009 15:47:28 +0000</pubDate>
		<guid isPermaLink="false">http://alex.ciobanu.org/?p=34#comment-469</guid>
					<description><![CDATA[Yes, you are right, I realized that after a few weeks I wrote the post but was too lazy to update it.

Thanks!]]></description>
		<content:encoded><![CDATA[<p>Yes, you are right, I realized that after a few weeks I wrote the post but was too lazy to update it.</p>
<p>Thanks!</p>
]]></content:encoded>
						</item>
						<item>
				<title>
				By: Krystian				</title>
				<link>https://alex.ciobanu.org/?p=34&#038;cpage=1#comment-466</link>
		<dc:creator><![CDATA[Krystian]]></dc:creator>
		<pubDate>Sun, 02 Aug 2009 11:33:21 +0000</pubDate>
		<guid isPermaLink="false">http://alex.ciobanu.org/?p=34#comment-466</guid>
					<description><![CDATA[Exception handling in this case are wrong, this can leads to unpredicted AVs.
You cannot use Exception (Ex-&#062;CaughtException) class after you leave except/end block (see System.AcquireExceptionObject comment), because it reference counter = 0 and it&#039;s destroyed, and after except/end block you&#039;re using pointer (CaughtException) to invalid memory block (as in most cases it will work &#039;fine&#039; unless other thread(s) will use that memory when FastMM alocates it, but you must NEVER assume that it will work fine, even in STA).

Isn&#039;t it better/easier to write Lock proc like this?

procedure Lock(const ALockObj: TObject; const AProc: TLockProc);
begin
  System.TMonitor.Enter(ALockObj);
  try
    AProc();
  finally
    System.TMonitor.Exit(ALockObj);
  end;
end;]]></description>
		<content:encoded><![CDATA[<p>Exception handling in this case are wrong, this can leads to unpredicted AVs.<br />
You cannot use Exception (Ex-&gt;CaughtException) class after you leave except/end block (see System.AcquireExceptionObject comment), because it reference counter = 0 and it&#8217;s destroyed, and after except/end block you&#8217;re using pointer (CaughtException) to invalid memory block (as in most cases it will work &#8216;fine&#8217; unless other thread(s) will use that memory when FastMM alocates it, but you must NEVER assume that it will work fine, even in STA).</p>
<p>Isn&#8217;t it better/easier to write Lock proc like this?</p>
<p>procedure Lock(const ALockObj: TObject; const AProc: TLockProc);<br />
begin<br />
  System.TMonitor.Enter(ALockObj);<br />
  try<br />
    AProc();<br />
  finally<br />
    System.TMonitor.Exit(ALockObj);<br />
  end;<br />
end;</p>
]]></content:encoded>
						</item>
			</channel>
</rss>
